### ISSUE TITLE
Support IP as license server name

### ISSUE THREAD

**Issue by mckel-9** [rpi-dotcio/phpLicenseWatcher#103]
**Is your feature request related to a problem? Please describe.**
While adding new servers, server names must be unique and in the form of `port@domain.tld`.
However, there are cases where a server might be only identified through an IP address like `port@12.345.67.890`.  Adding a server like this is currently not possible.

**Describe the solution you'd like**
Adding a server identified by an IP address like `port@12.345.67.890` should be possible. There should not be a restriction on the form of `port@domain.tld`.

**Comment by mcglow2** [comment]
In addition to IP the field should accept port@hostname without requiring a FQDN
