### ISSUE TITLE
No license message has been retrieved, how do I Dbug

### ISSUE THREAD

**Issue by tacop** [rpi-dotcio/phpLicenseWatcher#105]
ubuntu 20.04 php7.3 mysql

When using FlexLM lmutil binary, a warning message appears when setting cron

No servers have been polled. Make sure that license_util.php, licence_cache.php, and license_alert.php are setup on a cron schedule.

Set the license but no message is displayed

How can I exclude

**Comment by pbailie** [comment]
Check the install process on the front page of the repo:

>5. Setup cron to run scheduled tasks
>    ```
>    0 6 * * 1 php /var/www/html/license_alert.php >> /dev/null
>    0,10,20,30,40,50 * * * * php /var/www/html/license_util.php >> /dev/null
>    15 0 * * 1  php /var/www/html/license_cache.php >> /dev/null
>    ```

When license_util.php is run (which will poll the servers and license usage), then the message should go away.

**Comment by tacop** [comment]
Is there any way to check on my own?
It can be observed that the Server Administration Last Updated time is being updated, but the information still cannot be collected. The Status display DOWN Server Version is also blank.
Querying /var/log/cron.log shows as follows
Jan 7 09:40:01 licviewrv CRON[9179]: (root) CMD (root /var/www/html/license_util.php >> /dev/null)
Jan 7 09:50:01 licviewrv CRON[9266]: (root) CMD (root /var/www/html/license_util.php >> /dev/null)
Jan 7 10:00:01 licviewrv CRON[9370]: (root) CMD (root /var/www/html/license_util.php >> /dev/null)

**Comment by pbailie** [comment]
Your server is 192.168.1.95...
I have not yet completed the request for permitting the system to use a server by IPv4, yet.  That is being worked on in issue #103.  I am hoping to put up a PR very soon, though.  If you want to give my current version a try and see if it helps -- use the code from the "sever-name" branch.  (I typo'd "se**r**ver" -- 🤦‍♂️)

Also -- have a look at "check installation" under "admin"... and make sure that "lmutil binary" is marked good.  The fully resolved path for `lmutil` also needs to be properly referenced as `$lmutil_binary` within `config.php`.  The repo has a sample config file you can use as a guide.

If `lmutil` is setup OK, get to a command line, find `lmutil`, and try this to see if your license server is responding:
```bash
$ ./lmutil lmstat -c 5280@192.168.1.95
```

Hopefully this will help you find some answers.

**Comment by tacop** [comment]
> 您的伺服器是 192.168.1.95...我尚未完成允許系統通過 IPv4 使用伺服器的請求。這個問題[#103正在研究](https://github.com/rpi-dotcio/phpLicenseWatcher/issues/103)。不過，我希望能很快建立一個公關。如果你想試試我當前的版本，看看它是否有説明 - 使用"sever-name"分支中的代碼。（我打字錯誤"se**r**ver" -🤦 ♂️)
> 
> 另外 - 看看「管理員」下的「檢查安裝」...並確保「lmutil binary」被標記為良好。的完全解析路徑也需要正確引用，如 在 中一樣。該儲存庫有一個範例設定檔，可用作指南。`lmutil``$lmutil_binary``config.php`
> 
> 如果 設定為 OK，請轉到命令列，找到 ，然後嘗試以下操作以查看您的授權伺服器是否正在回應：`lmutil``lmutil`
> 
> ```shell
> $ ./lmutil lmstat -c 5280@192.168.1.95
> ```
> 
> 希望這能説明你找到一些答案。


Double-check that still no messages are loaded
Maybe the problem is in my authorization service 

-------------------------------------------------------
<html>
<body>
<h1 style="box-sizing: border-box; margin: 20px 0px 10px; font-size: 36px; font-family: Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Check PHPlicensewatcher Installation</h1><hr style="box-sizing: content-box; height: 0px; margin-top: 20px; margin-bottom: 20px; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); color: rgb(0, 0, 0); font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(0, 0, 0); font-family: Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This will check whether PHPlicensewatcher has been properly installed. This is not an exhaustive check but checks for common installation and configuration issues.</p>

TEST | VALUE | RESULT
-- | -- | --
PHP Version At Least 7.3.0 | 7.4.3 | ✔ GOOD
64-bit Unix Timestamp | 64-bit | ✔ GOOD
config.php | Readable | ✔ GOOD
lmutil binary | Is Executable | ✔ GOOD
monitorlm binary | Not Executable (maybe check permissions?) | ✖ FAIL
Database Connectivity | Connection OK | ✔ GOOD


</body>
</html>
---------------------------------------------------------------------------------------
<html>
<body>


Name | Label | Licensing | Is Active | Status | Server Version | Last Updated
-- | -- | -- | -- | -- | -- | --
TLSRV | Flexlm | True | DOWN |   | 01/10/2022 09:40am


</body>
</html>
-------------------------------------------------------------------------------

CLI  ./lmutil lmstat -c 5280@192.168.1.95
root@licviewrv:/usr/local/bin/lmutil# ./lmutil lmstat -c 5280@192.168.1.95
lmutil - Copyright (c) 1989-2020 Flexera. All Rights Reserved.
Flexible License Manager status on Mon 1/10/2022 09:43

License server status: 5280@tlsrv
    License file(s) on tlsrv: D:\Cadence\LicenseManager\license.dat:

     tlsrv: license server UP (MASTER) v11.9

Vendor daemon status (on tlsrv):

    cdslmd: UP v11.9

root@licviewrv:/usr/local/bin/lmutil#

Cron log
Jan 10 09:33:32 licviewrv anacron[1709]: Anacron 2.3 started on 2022-01-10
Jan 10 09:33:32 licviewrv anacron[1709]: Normal exit (0 jobs run)
Jan 10 09:39:01 licviewrv CRON[1718]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Jan 10 09:40:01 licviewrv CRON[1770]: (root) CMD (php /var/www/html/license_util.php >> /dev/null)
Jan 10 09:40:01 licviewrv CRON[1769]: (root) MAIL (mailed 573 bytes of output but got status 0x00ff from MTA#012)

will still show 
No servers have been polled. Make sure that license_util.php, licence_cache.php, and license_alert.php are setup on a cron schedule

**Comment by pbailie** [comment]
>Added I found apacher2 log error
>sh: 1: /usr/local/bin/lmutil: Permission denied
>Is it a permissions issue
>Tip: flexlm is the windows version

I'm not sure I fully follow...
Your first post says you are running on Ubuntu 20.04.  But you have the Windows version of flexlm?

Can you get a Linux version of flexlm?  Because as much as I would like to help -- I can't get involved with Windows executable compatibility tools.  e.g. WINE

**Comment by pbailie** [comment]
Reading through your notes again -- is it that your license server is Windows, but you are running `lmutil` in Linux, and Apache is reporting a permissions issue with `lmutil`?

If that is correct, what I can advise is that Apache's default user account in Ubuntu is `www-data`, which does need permission to execute `lmutil`.

**Comment by tacop** [comment]
> 再次閱讀您的筆記 - 您的許可證伺服器是Windows，但是您在Linux中運行，並且Apache報告了許可權問題嗎？`lmutil``lmutil`
> 
> 如果這是正確的，我可以建議的是，Apache在Ubuntu中的預設用戶帳戶是 ，它確實需要文件許可權才能執行。`www-data``lmutil`

**Comment by tacop** [comment]
> Reading through your notes again -- is it that your license server is Windows, but you are running `lmutil` in Linux, and Apache is reporting a permissions issue with `lmutil`?
> 
> If that is correct, what I can advise is that Apache's default user account in Ubuntu is `www-data`, which does need file permission to execute `lmutil`.

My FlexLM is installed on windows server
phpLicenseWatcher installed on Ubuntu server 20.4
permission i try to execute
sudo chown -R www-data: /usr/local/bin/lmutil
sudo chown -R www-data: /var/www/html
But still inquiring why status shows down

**Comment by tacop** [comment]
> 再次閱讀您的筆記 - 您的許可證伺服器是Windows，但是您在Linux中運行，並且Apache報告了許可權問題嗎？`lmutil``lmutil`
> 
> 如果這是正確的，我可以建議的是，Apache在Ubuntu中的預設用戶帳戶是 ，它確實需要文件許可權才能執行。`www-data``lmutil`

**Comment by tacop** [comment]
> 再次閱讀您的筆記 - 您的許可證伺服器是Windows，但是您在Linux中運行，並且Apache報告了許可權問題嗎？`lmutil``lmutil`
> 
> 如果這是正確的，我可以建議的是，Apache在Ubuntu中的預設用戶帳戶是 ，它確實需要文件許可權才能執行。`www-data``lmutil`

**Comment by tacop** [comment]
> Reading through your notes again -- is it that your license server is Windows, but you are running `lmutil` in Linux, and Apache is reporting a permissions issue with `lmutil`?
> 
> If that is correct, what I can advise is that Apache's default user account in Ubuntu is `www-data`, which does need file permission to execute `lmutil`.

It looks like it's a PHP.ini problem so far
Part of it has been excluded, can you help me confirm the following
Execute php license_util.php The following content will appear

PHP Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in /var/www/html/license_util.php: 206
Stack trace:
#0 /var/www/html/license_util.php(206): mysqli->query()
#1 /var/www/html/license_util.php(171): db_cleanup()
#2 /var/www/html/license_util.php(9): update_licenses()
#3 {main}
   thrown in /var/www/html/license_util.php on line 206
