### ISSUE TITLE
Install HTML_Table (Debian)

### ISSUE THREAD

**Issue by dcpc007** [rpi-dotcio/phpLicenseWatcher#11]
on a debian 9 with php7.0 i already install php-pear package
But check_installation.php says no HTML_Table. 

How to install it (via package if possible)

**Comment by dcpc007** [comment]
Official doc : https://pear.php.net/package/HTML_Table

but pear install HTML_Table got a : 

> No release available for package "pear.php.net/HTML_Table"

**Comment by e549971** [comment]
Any news ?

**Comment by pbailie** [comment]
PR #20 includes `composer.json` for installing HTML Tables via composer.  It's intended for the Vagrant testing server, but I don't anticipate any reason why this wouldn't work elsewhere.

**Comment by pbailie** [comment]
Per #38, Pear/HTML_Table dependency has been replaced by a local html_table class.  This work has been committed to the database branch, but has yet to be merged into master.
