### ISSUE TITLE
error in your SQL syntax with latest version

### ISSUE THREAD

**Issue by LiamSx45** [rpi-dotcio/phpLicenseWatcher#117]
**Describe the bug**
license_util.php will not run with latest MySQL.

` php-lw@phplw:/var/www/html/phplicensewatcher O php-lw@phplw:/var/www/html/phplicensewatcher$phplicenseutil.php PHP Fatal error: Uncaught mysqli_sql exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near "at line 1 in /var/www/html/phplicensewatcher/licenseutil.php:206 Stack trace: #0 /var/www/html/phplicensewatcher/license_util.php(206):mysqli->query() #1 /var/www/html/phplicensewatcher/license_uttl.php(171):db_cleanup() #2 /var/www/html/phplicensewatcher/license_uttl.php(9):updatelicenses) #3 (main} thrown in /var/www/html/phplicensewatcher/license util.php on line 206`

**To Reproduce**
1. Go to 'terminal'
2. Change directory to install location
3. Type `php license_util.php`
4. See an error

**Expected behavior**
supposed to run the file and update the license servers. Instead it gives a syntax error and updates the servers as DOWN

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [firefox]
 - Version [ubuntuo.20.04.3]
 - SQL Version: `mysql Ver 8.0.28-Oubuntuo.20.04.3 for Linux on x86 64 ((Ubuntu))`

**Additional context**

**Comment by pbailie** [comment]
Unfortunately, I am unable to recreate the bug.  I just ran license_util without error and the results were available in the system.  My test was done with 
* `Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-107-generic x86_64)`
* `mysql  Ver 8.0.28-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))`

Last time I tried to help with a database error I could not reproduce, it turned out to be a permissions issue in MySQL.  The user account that is managing phplw's data needs to have all privileges to the database.  Could you check that and let me know if it helped or not.  Thanks.

**Comment by pbailie** [comment]
I did more testing and I finally was able to recreate the error on a very specific condition.  That being when there are no features or licenses data in the database.  In which case, the query gets malformed like so...

`ALTER TABLE features AUTO_INCREMENT = ;`

The auto_increment value is absent, thus the syntax error.  The purpose of the query is to help prevent the table's auto-increment ID from creeping as that sometimes happens within InnoDB.

I can add an error trap to provide more clarity to the problem, but I'll add that the system avails nothing without features and licenses data, regardless.

Some more notes...
When you add a new server, it's not necessary to manually provide features and licenses data.  That should happen automatically when the server is polled by license_util.php.  But if there is a problem polling the license server, then features and license data doesn't get added.  There is a features administrative page to manually add and edit features.  But licenses are defined by both the servers polled and the features managed by each server, so it becomes necessary that the server can be polled.

So please check that at least one server is listed in the server administration page, _and_ that server can be reached.  e.g. The licensing server is permitted to — and will respond to — FlexLM's `lmutil` on the command line.
