### ISSUE TITLE
Installation documentation update

### ISSUE THREAD

**Issue by dcpc007** [rpi-dotcio/phpLicenseWatcher#12]
Improve prerequisites and installation steps

**Comment by DVCoder** [comment]
Could anyone provide instructions on how they were able to get phpLicenseWatcher running? I'm using CentOS 7 and I have been installing a lot of additional packages, and I'm still not able to get it to work. I'm stuck where the config.php is not able to read the database.

**Comment by mcglow2** [comment]
@DVCoder can you send me any php error messages from the page or apache error logs?  

Putting this at the top of the index.php will print the errors to the page
ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
error_reporting( E_ALL);

**Comment by JulienWegner** [comment]
I have also problems to get it work correctly on rhel 8 ...
I can't see any graphs  and some pages return DB Error: extension not found.
I put to index.php 

ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
error_reporting( E_ALL);

and I get:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; HTML_Common has a deprecated constructor in /usr/share/pear/HTML/Common.php on line 33

check_installation.php is fine..only warnings for LUM..but i only want to monitor FlexLM

Could someone support me?
Julien

**Comment by mcglow2** [comment]
Updated version on the main branch has very few external dependencies now and should be much easier to install.
