### ISSUE TITLE
Unknown column 'lm_default_usage_reporting' in 'field list'

### ISSUE THREAD

**Issue by tacop** [rpi-dotcio/phpLicenseWatcher#132]
ubuntu 22.04
apt update && git pull
Server Administration new modification error occurred
----------
Unknown column 'lm_default_usage_reporting' in 'field list'
----------
Do you need to add a database field?

**Comment by pbailie** [comment]
You do need the column added.  An SQL script to add this column is available in `database/migrations/migration-02.sql`.

**Comment by tacop** [comment]
> 您確實需要添加該列。添加此列的 SQL 腳本在`database/migrations/migration-02.sql`.

**Comment by tacop** [comment]
> You do need the column added. An SQL script to add this column is available in `database/migrations/migration-02.sql`.

Thanks it's resolved....
In addition, if the custom Label name will be overwritten
The previous version changed the Label name, otherwise a new one will be generated
