### ISSUE TITLE
Check the License monitoring module quantity and there is No total quantity.

### ISSUE THREAD

**Issue by tacopchang** [rpi-dotcio/phpLicenseWatcher#141]
**Describe the bug**
Please help check the problem
License monitoring module statistics are incorrect
There is no total for different authorized hosts and the same module name. Only the quantity used by a single host is displayed...

**Expected behavior**
Two license servers have the same module function and the same name.
, check License monitoring module statistics. Because the same module function names should be totaled, currently only the usage number of a single license server is displayed.

**Comment by tacopchang** [comment]
Can you help me?

**Comment by pbailie** [comment]
phpLicenseWatcher is not designed to poll multiple license servers of the same name.

**Comment by tacop** [comment]
> phpLicenseWatcher 的設計目的不是輪詢多個同名的授權伺服器。

thanks for the reply 
Not the same server name
They are the same authorization file, but the same name is detected. Statistics only show one.
Please help again

**Comment by pbailie** [comment]
I apologize for the lengthy delay.

If I understand you correctly:  You have one feature, but it is managed by two different servers.

By our database design, a distinct license is defined by one server _and_ one feature.
![Alt text](https://github.com/rpi-dotcio/phpLicenseWatcher/raw/assets/db_schema.png?raw=true "Database ER Diagram")
Therefore, one feature managed by two different servers technically counts as two distinct licenses, so by specification these license checkout counts are not added together.  This is the intended behavior.
