### ISSUE TITLE
Move any dependencies to composer

### ISSUE THREAD

**Issue by mcglow2** [rpi-dotcio/phpLicenseWatcher#15]
move any dependencies from pear to composer.  If possible use the same the libraries, I believe there are HTML table and Database libraries in use.  If not possible recommend some alternatives.

**Comment by pbailie** [comment]
`pear/html_table` requires `pear/html_common`.  However, composer reports:
```
  Problem 1
    - The requested package pear/html_common ^1.2.5 exists as pear/html_common[dev-topics/composer-for-pear, dev-trunk] but these are rejected by your constraint.
  Problem 2
    - Installation request for pear/html_table ^1.8.4 -> satisfiable by pear/html_table[v1.8.4].
    - pear/html_table v1.8.4 requires pear/html_common ^1.2.5 -> no matching package found.
```
So... `pear/html_table` is there, but not there.  

Adding constraint `@dev` or property `"minimum-stability": "dev"` doesn't help.  My guess is that `pear/html_common` isn't appropriately version tagged in packagist.  Meanwhile, it has been dormant for years.  

Good news is that composer can retrieve packages directly from pear.  We may still want to find alternative libraries with newer code.

**Comment by mcglow2** [comment]
I am fine with you adding issues for, and refactoring out any use of the pear libraries.

**Comment by pbailie** [comment]
Recent work has actually removed all pear dependencies per #38.  Composer no longer needed.  Closing issue.
