### ISSUE TITLE
Add caching to lmutil calls

### ISSUE THREAD

**Issue by ghost** [rpi-dotcio/phpLicenseWatcher#2]
Add a caching layer around lmutils calls to make UI more responsive

**Comment by pbailie** [comment]
disk caching lmutil calls for currently used licenses (in details.php) does not provide a significant UI speedup.  We may have to examine the quality of the regex patterns.

**Comment by mcglow2** [comment]
I think we can close this now that we use the database for the index.php list of servers.  I think most the delay was in enumerating each separate one.
