### ISSUE TITLE
Add warning if no new data is being seen

### ISSUE THREAD

**Issue by mcglow2** [rpi-dotcio/phpLicenseWatcher#28]
Check that cron jobs are running by looking in the database for recent data.

**Comment by pbailie** [comment]
Just looking at the status page is a good clue if the cron jobs are running.  Every run will update the server update timestamps in the database, and consequently shown on the status page.

**Comment by pbailie** [comment]
I can set up a notice to setup cron when all servers are showing "not polled" (e.g. first run of the system).
