### ISSUE TITLE
Auto populate features and licenses table

### ISSUE THREAD

**Issue by mcglow2** [rpi-dotcio/phpLicenseWatcher#32]
Method to auto add rows to the feature and licenses table for licenses on a given server.  Updates to usage table fail for entries that do not already exist.  features.show_in_lists should default to 0 I believe

Running the http://localhost:50080/license_util.php page to generate entries in the usage table did not work for new server added to servers table.  Query below needs  feature and licenses populated first.  This can be complicated, and a lot of features may be needed.  I suggest that we detect the insert failing for this error and add an insert that setups the proper values.

INSERT INTO `usage` (`license_id`, `time`, `num_users`) SELECT `licenses`.`id`, '2020-10-14 17:01:00', 6 FROM 
`licenses` JOIN `servers` ON `licenses`.`server_id`=`servers`.`id` JOIN `features` 
ON `licenses`.`feature_id`=`features`.`id` WHERE `servers`.`name`='7788@licsrvr2.arc.rpi.edu' AND `features`.`name`='moe';

**Comment by pbailie** [comment]
As an aside...  `database/update_01.sql` will take existing servers, features, and licenses from the old schema, deduplicate where needed, and convert existing data to the new schema (it can take several minutes to run).  It has worked in my limited testing.  I also was able to run `license_util.php` successfully, afterwards.
