### ISSUE TITLE
Remove Pear Dependencies

### ISSUE THREAD

**Issue by pbailie** [rpi-dotcio/phpLicenseWatcher#38]
Composer v2 rejects the Pear repository and Pear packages in Packagist are not sufficiently maintained.  More specifically, the dependency chain in Packagist for pear/html_table is broken.

We need to move away from Pear altogether.  As it currently stands, this will also mean moving away from Composer, although we could come back to using Composer should a new need arise.

Vagrant provision will also need to be adjusted.

**Comment by nigelhorne** [comment]
I've done a git pull and things are now getting closer, thanks.  We now see this error:

`[Tue Nov 17 13:22:08.974587 2020] [proxy_fcgi:error] [pid 10089:tid 140484957632256] [client x.x.x.x:54206] AH01071: Got error 'PHP message: PHP Notice:  Undefined variable: error in /var/www/x.x.x.x/license/common.php on line 124PHP message: PHP Notice:  Undefined property: mysqli::$ in /var/www/x.x.x.x/license/common.php on line 124'`

**Comment by pbailie** [comment]
I believe I've fixed that in 245c35d.  There is still more for me to do.

**Comment by nigelhorne** [comment]
Thanks I've done a git pull and it hasn't updated.

**Comment by nigelhorne** [comment]
Thanks - a little closer:

`Table 'licences.servers' doesn't exist`

Should that be singular?

```
MariaDB [(none)]> use licences;
Database changed
MariaDB [licences]> show tables;
+--------------------+
| Tables_in_licences |
+--------------------+
| feature            |
| flexlm_events      |
| license_usage      |
| licenses_available |
| server             |
| server_status      |
+--------------------+
6 rows in set (0.00 sec)
```

**Comment by pbailie** [comment]
Table `servers` (plural) is correct.  It's part of the schema change.  Tables is supposed to look like this:
```
mysql> show tables;
+-------------------+
| Tables_in_vagrant |
+-------------------+
| available         |
| events            |
| features          |
| licenses          |
| servers           |
| usage             |
+-------------------+
6 rows in set (0.00 sec)
```
I've also uploaded an ER diagram that you can view in the database folder in the database branch.

**Comment by nigelhorne** [comment]
So, should I just run the "update_01.sql" script?

**Comment by nigelhorne** [comment]
Since I have no data I blew the database away and tried to recreate.  This is what I got:

```
mysql -u lic_root -h xxxx licenses -f -p < phplicensewatcher.sql
Enter password:
ERROR 1064 (42000) at line 14: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = u' at line 7
ERROR 1067 (42000) at line 32: Invalid default value for 'last_updated'
ERROR 1064 (42000) at line 55: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '
  INDEX `fk_licenses_features1_idx` (`feature_id` ASC) VISIBLE,
  CONSTRAINT `f' at line 6
ERROR 1273 (HY000) at line 83: Unknown collation: 'utf8mb4_0900_as_cs'
ERROR 1273 (HY000) at line 105: Unknown collation: 'utf8mb4_0900_as_cs'
ERROR 1273 (HY000) at line 125: Unknown collation: 'utf8mb4_0900_as_cs'
```

**Comment by nigelhorne** [comment]
It's strange, it's almost like the file has backprimes instead of singlequotes.

**Comment by pbailie** [comment]
@nigelhorne 

> So, should I just run the "update_01.sql" script?
> 
> `mysql -u lic_root -h xxx licenses -p < update_01.sql`

The update script was intended to convert from the old schema to new schema while preserving most data (some data was discarded by specification).  But it has slightly fallen out of parity with the current schema.  (I do tweak the schema as I find a need to.)  I wrote the update script for RPI's use, only to be later told that it wasn't really needed.  And since it is a PITA to maintain, it's probably going to be dropped.

If enough need is expressed in the update script (and @mcglow2 is OK with it) -- I can get the update script back to parity.  Doubtful it would ever be a priority task, and right now that "expressed need" stands at zero, anyway.

> Since I have no data I blew the database away and tried to recreate. This is what I got:
> 
> ```
> mysql -u lic_root -h xxxx licenses -f -p < phplicensewatcher.sql
> Enter password:
> ERROR 1064 (42000) at line 14: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
> ENGINE = InnoDB
> AUTO_INCREMENT = 1
> DEFAULT CHARACTER SET = utf8mb4
> COLLATE = u' at line 7
> ERROR 1067 (42000) at line 32: Invalid default value for 'last_updated'
> ERROR 1064 (42000) at line 55: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '
>   INDEX `fk_licenses_features1_idx` (`feature_id` ASC) VISIBLE,
>   CONSTRAINT `f' at line 6
> ERROR 1273 (HY000) at line 83: Unknown collation: 'utf8mb4_0900_as_cs'
> ERROR 1273 (HY000) at line 105: Unknown collation: 'utf8mb4_0900_as_cs'
> ERROR 1273 (HY000) at line 125: Unknown collation: 'utf8mb4_0900_as_cs'
> ```

`utf8mb4_0900_as_cs` is a valid collation (ordering) for MySQL.  It stands for 4 byte UTF8, accent-sensitive (like diacritic marks found on some European characters) and case sensitive.  The default `utf8mb4` would have been accent and case insensitive.

To help maintain the database schema, I am using Oracle's MySQL Workbench Community Edition (which is GPL).  It may not be well tuned to MariaDB.  I don't mind looking for compromise settings so long as incompatibilities with MariaDB are relatively simple.  (I suspect collation should be simple enough -- I'll take a look at it soon)

> It's strange, it's almost like the file has backprimes instead of singlequotes.

MySQL uses backticks to denote database entities.  As opposed to single-quotes for text data.  I sometimes (not always) get errors thrown when backticks are missing -- so my code has them just to be thorough.

I should be back at this tomorrow (Wed 11/18/20).  Thanks for the feedback.
