### ISSUE TITLE
cronjobs on master branch

### ISSUE THREAD

**Issue by nigelhorne** [rpi-dotcio/phpLicenseWatcher#40]
I don't know if this has already been fixed in the database branch.  I'm documenting just in case:

```
php /var/www/xxxx/license/license_util.php
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/pear/DB.php on line 774
```

license_cache.php has the same problem.

**Comment by pbailie** [comment]
pear/DB is one of the dependencies I am currently removing from the project per #38.  This is one more reason to do so.  😉
