### ISSUE TITLE
No Reliable INSERT Into Events Table

### ISSUE THREAD

**Issue by pbailie** [rpi-dotcio/phpLicenseWatcher#41]
The `events` table in Database branch (which evolved from `flm_events` in Master) does not have any reliable data inserts.  `parselogs.php` has an `INSERT` query, but it relies on log files that do not get written.  This will affect some views (e.g. FlexLM denials and checkouts)  by showing a table with headers, but no data.

This is possibly due to an incomplete feature from the original fork.

**Comment by mcglow2** [comment]
Both this table, and the parselogs.php file can be removed

**Comment by pbailie** [comment]
How about the FlexLM checkouts and denials pages (`checkouts.php` and `denials.php`)?  They don't display anything meaningful without events data.

**Comment by mcglow2** [comment]
Maybe we move them all to a branch.  I can see getting that functionality back would be useful for some people.  Our logs are all on remote servers so our personal challenge would be to get the logs first.
