### ISSUE TITLE
php-gd extension requirement

### ISSUE THREAD

**Issue by pbailie** [rpi-dotcio/phpLicenseWatcher#44]
Graphs are drawn with Javascript via Google Visualization.  That shouldn't make php-gd a requirement.  Do we have another reason for php-gd or can it be dropped as a stated requirement?  (I will also try some testing to see how things go without php-gd)

**Comment by mcglow2** [comment]
Probably no longer needed.  I moved the graphs to google api but probably never removed that requirement from the docs.
