### ISSUE TITLE
Reduce disk usage

### ISSUE THREAD

**Issue by mcglow2** [rpi-dotcio/phpLicenseWatcher#45]
Look into changing these values from integers to unsigned small ints.  I believe these max values of 65000 are still reasonable and will further cut our data usage by 50%, possibly even 75%.

licenses.id TO UNSIGNED small INT
usage.license_id TO UNSIGNED small INT
usage.num_users TO unisgned small INT

**Comment by pbailie** [comment]
Following this plan, looks like `available.license_id` should also be unsigned small int.

**Comment by pbailie** [comment]
How about `licenses.id` and `features.id`?

**Comment by pbailie** [comment]
Completed in PR #51
