### ISSUE TITLE
Dont record values from some features

### ISSUE THREAD

**Issue by mcglow2** [rpi-dotcio/phpLicenseWatcher#46]
Add a flag to the features table that if false, we don't track license usage for that feature.

**Comment by pbailie** [comment]
`license_util.php` auto fills in missing features.  Should newly autofilled features have tracking default to true or false?  (while we're at it -- also, how about `features.show_in_lists`?)

**Comment by mcglow2** [comment]
Default Tracking and show in lists to true

**Comment by pbailie** [comment]
Completed in PR #51
