### ISSUE TITLE
Expiration Date

### ISSUE THREAD

**Issue by kown7** [rpi-dotcio/phpLicenseWatcher#52]
**Describe the bug**
It picks the wrong licenses to display.

`lmstat -ai` output:
```
Feature                         Version     #licenses    Vendor        Expires
_______                         _________   _________    ______        ________
msimcompare                     2014.020     0           mgcld         31-jan-2023
msimcompare                     2021.010     6           mgcld         29-jan-2021
msimcompare                     2021.030     2           mgcld         15-mar-2021
```

**Expected behavior**
I'd like to see this (29-jan-2021) in the overview, instead I get the following. It's probably the last in the list.

>  msimcompare | mgcld | 8 | 2 license(s) expire(s) in 53 day(s) Date of expiration: 15-mar-2021

**Additional context**
Otherwise a brilliant tool.

**Comment by pbailie** [comment]
Fixed in PR #55
