### ISSUE TITLE
Wrong "Computer: /dev/tty" shown

### ISSUE THREAD

**Issue by rems0** [rpi-dotcio/phpLicenseWatcher#79]
Hi all,

first of all, thanks for this nice license monitor!

On my setup I have two license servers, one delivering licenses for two vendors, cdlmd and ugslmd.
For ugslmd the "Computer" entry gets shown ok.
For cdlmd "Computer" shows always "/dev/tty".
See attached lmstat output.

Also, for the example output attached, for the DOEtoken feature, several licenses get used on the same node, then number is shown at the end of line on the output. That number would be very useful also on the details page.
    user6 node0004.cluster /dev/tty (v2019.10) (company-lic/6006 2330), start Wed 5/26 15:32, **109 licenses**
    user5 c1n36 /dev/tty (v2019.10) (company-lic/6006 5317), start Wed 5/26 16:16, **5 licenses**

Kind regards,
Richard
[lmutil_lmstat-a.txt](https://github.com/rpi-dotcio/phpLicenseWatcher/files/6549148/lmutil_lmstat-a.txt)

**Comment by uChoh5fe** [comment]
Hi,
I fixed it with

```
diff --git a/details.php b/details.php
index 3bd47bd..33d552b 100644
--- a/details.php
+++ b/details.php
@@ -245,8 +245,13 @@ HTML;
                             // Output the user line
                             $user_line = $used_license;
                             $user_line_parts = explode( ' ', trim($user_line) );
+                            $myhost = explode( '.', trim($user_line_parts[1]) );
+
+                                                       
                             $user_line_formated = "<span>User: ".$user_line_parts[0]."</span> ";
-                            $user_line_formated .= "<span>Computer: ".$user_line_parts[2]."</span> ";
+                            #$user_line_formated .= "<span>Computer: ".$user_line_parts[2]."</span> ";
+                            $user_line_formated .= "<span>Computer: ".$myhost[0]."</span> " ;
+
                             $table->add_row(array("", "", $user_line_formated, $time_difference), $class);
                         }
                     }

```
give it a try. Maybe it depends on the used lmutil tool version?

**Comment by rems0** [comment]
Hi, yes, that fixed it, thanks!

In my case, lmutil version is:
# lmutil -v
Copyright (c) 1989-2016 Flexera Software LLC. All Rights Reserved.
lmutil v11.14.0.2 build 191018 x64_lsb

Thanks,
Richard

**Comment by pbailie** [comment]
I am developing/testing with a different version of `lmutil`, but I did confirm that the wrong field was being captured.  I implemented a fix while working on a different, but partly related issue.
