### ISSUE TITLE
Complete And Normalize Database Schema

### ISSUE THREAD

**Issue by pbailie** [rpi-dotcio/phpLicenseWatcher#8]
Database schema is currently only a bunch of tables.  Schema needs to be completed with proper entity relationships and normalized (I propose normalizing to BCNF).

**Comment by mcglow2** [comment]
Some general notes on items to change in schema

1. Remove the flexlm_ or license(s)_ notation on table names and remove tables names in field names. ie licenses_available.flmavailable_date would become available.date
2.  Change character set to UTF-8
3.  license_usage.flmusage_date and license_usage.flmusage_time can be combined into single datetime field
4. license_usage.flmusage_server and licenses_available.flmavailable_server should be proper integer foreign keys against server.id
5. flexlm_events and server_status are not currently used should be fixed and kept in the schema

**Comment by pbailie** [comment]
We're also going to need an `is_active` boolean (tinyint) field for servers, so we don't have to delete servers that are retired, therefore preserving historical data.

**Comment by pbailie** [comment]
@mcglow2 

My work in the `database` branch now has the database ER diagram looking like this:
![db_schema](https://user-images.githubusercontent.com/12703624/79590499-1b0cbc00-80a5-11ea-9ff1-957b876f085d.png)

Now I am wondering if we should tie `available.product` and `usage.product` to `features.id` (and converting to appropriate data types)?
![proposed01](https://user-images.githubusercontent.com/12703624/79590639-53ac9580-80a5-11ea-9374-c5f2ff3440f3.png)



Looks to me, though, that used licenses could exceed available licenses...?  Thoughts?

And could we merge `status` table into `servers` table?

**Comment by mcglow2** [comment]
1. Yes, I believe fields in status could move to servers table.  
2. events table is not used by working code but should have a relation to server.id as they would tie to a single server if that code is ever fixed
3.  Features table should have a server id foreign key , features are per server .  Dont think anything previously made that clear though.
4. WRT "Looks to me, though, that used licenses could exceed available licenses...? " that is true, we dont need to worry about it though.
