### ISSUE TITLE
[Feature request] Example .htaccess file

### ISSUE THREAD

**Issue by rems0** [rpi-dotcio/phpLicenseWatcher#80]
Hi all,

attached a htaccess example file that I am using to block access to phplicensewatcher admin pages.
Perhaps this file can be added into the git tree as an example.
It works for me, but there may be errors or missing bits in there. Handle with care. :)

Kind regards,
Richard
[htaccess-example.txt](https://github.com/rpi-dotcio/phpLicenseWatcher/files/6549192/htaccess-example.txt)

**Comment by mcglow2** [comment]
Thank you for this example.  It shows a public / admin separation use case that is different than how we use this software.  I have added this example, and some others to a wiki page at https://github.com/rpi-dotcio/phpLicenseWatcher/wiki/Example-Apache-Configurations
