### ISSUE TITLE
Heatmap License Usage over 24-Hours

### ISSUE THREAD

**Issue by kown7** [rpi-dotcio/phpLicenseWatcher#84]
Currently, the tool neatly shows peak license usage over time. From this we can derive our need for licenses.

However, peak license usage isn't necessarily the most relevant, e.g., usage at night by CI-tools. 

Perhaps something like [1].

[1]: https://stackoverflow.com/questions/34755746/fill-a-heat-map-24h-by-7days-in-ggplot2

**Comment by mcglow2** [comment]
This is an interesting suggestion and we would accept a pull request implementing something like this into the project.  An option to use this instead of the line chart on the monitor_detail.php page would make sense.

**Comment by scs-kno** [comment]
#102 solves this

**Comment by scs-kno** [comment]
See #102 
This should be fixed there.

**Comment by kown7** [comment]
See #102; should be fixed there.
