### ISSUE TITLE
Authenticated email

### ISSUE THREAD

**Issue by pbailie** [rpi-dotcio/phpLicenseWatcher#96]
phplw was internally flagged for sending unauthenticated email (for sending expiring license reports).  Some organizations may not approve.  This issue is a feature request to add an option to mail expiring license reports through authenticated email.

**Comment by mcglow2** [comment]
I agree that it would be good at add support for authenticated email as many installations may require it.

**Comment by mcglow2** [comment]
I think PHPMailer is the go to composer library for many people.  https://github.com/PHPMailer/PHPMailer
